#!/usr/bin/env python3

from netmiko import ConnectHandler

ip = input("Introduzca la direcci      n IP del dispositivo: ")
username = input("Introduzca el nombre de usuario: ")
password = input("Introduzca la contrase      a: ")

device = {
    'device_type': 'cisco_ios',
    'ip': ip,
    'username': username,
    'password': password
}


with ConnectHandler(**device) as net_connect:
    output = net_connect.send_command('show tech', read_timeout=120)



with open('configuracion.txt', 'w') as file:
    file.write(output)
